---
platform: linux
image_resource:
  type: docker-image
  source: {repository: qibobo/autoscaler-deploy, tag: v1}
inputs:
- name: cf-deployment
- name: app-autoscaler-ci
run:
  path: app-autoscaler-ci/autoscaler/scripts/deploy-cf.sh